name: Remove old artifacts
on:
  schedule:
    - cron: '0 3 * * *' # Every day at 3am
  workflow_dispatch:
jobs:
  remove-old-artifacts:
    name: Remove old artifacts
    runs-on: ubuntu-latest
    timeout-minutes: 10 # stop the task if it takes longer

    steps:
    - name: Remove old artifacts
      uses: c-hive/gha-remove-artifacts@v1
      with:
        age: '5 minutes'
        skip-tags: true
        skip-recent: 1
